[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[project]
name = "fragment-explorer"
version = "0.1.0"
description = "fragment-explorer"
keywords = ["proteomics"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
    "Development Status :: 5 - Production/Stable"
]
requires-python = ">=3.12"
dependencies = [
    "brain-isotopic-distribution>=1.5.17",
    "logomaker>=0.8.7",
    "matplotlib>=3.10.3",
    "ms-deisotope>=0.0.59",
    "ms-peak-picker>=0.1.46",
    "networkx>=3.4.2",
    "numba>=0.61.2",
    "numpy>=2.2.5",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "plotly[express]>=6.0.1",
    "psm-utils>=1.4.1",
    "pyteomics[XML]>=5.0.0",
    "pyteomics-cythonize>=0.2.9",
    "scikit-learn>=1.6.1",
    "scipy>=1.15.3",
    "spectrum-utils>=0.4.2",
    "streamlit>=1.45.1",
    "tqdm>=4.67.1",
    "pyvis>=0.3.2",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.8",
]

[project.scripts]
fragment-explorer = "fragment_explorer:main"
